Improve handling of user header
stan-dev/cmdstanr pull request #818
Opened 2023-08-10 13:43 UTC by martinmodrak

#### Submission Checklist

- [ ] Run unit tests
- [x] Declare copyright holder and agree to license (see below)

I have run unit tests and I get some failures, but I get the same failures on master, so presumably this is not a problem with the PR...

#### Summary

Resolves #812 and #813 (as the fix to #813 requires changes needed to fix #812, I've made a single PR for both)

#### Copyright and Licensing

Please list the copyright holder for the work you are submitting
(this will be you or your assignee, such as a university or company):
Institute of Microbiology of the Czech Academy of Sciences

By submitting this pull request, the copyright holder is agreeing to
license the submitted work under the following licenses:

- Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)
- Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

2023-08-16 19:29 UTC, martinmodrak commented
@rok-cesnovar @jgabry  So this appears ready to merge. Beyond the changes to header handling I made some tweaks to tests. In particular, there are now `expect_compile` and `expect_no_recompilation` helpers that standardize the behaviour to have file existence and modifications time checked at all places and not rely only on messages (which I am not sure are actually checked when testing within the CI environment as they are bound to interactive mode). I've also added a `dry_run` argument to `$compile` that let's us test argument handling and messages without actually trigerring the C++ compilation. Both could probably be used more extensively, but I didn't want to pollute the PR too much. If you like the concept, I will open a separate issue + PR on applying this more broadly.

2023-08-16 23:38 UTC, jgabry requested changes
Thanks @martinmodrak. I made a few suggestions but I'm just being nitpicky to match style, no substantive changes. @rok-cesnovar has written much more of the `compile` method code than I have so let's see if he has any other feedback, but this looks good to me.  

> I've also added a `dry_run` argument to `$compile` that let's us test argument handling and messages without actually trigerring the C++ compilation. 

Good idea.

> Both could probably be used more extensively, but I didn't want to pollute the PR too much. If you like the concept, I will open a separate issue + PR on applying this more broadly.

Great, yeah I like the concept.

2023-08-16 23:38 UTC, jgabry commented on R/model.R
> +#' @param dry_run (logical) If TRUE, the code will do all checks before compilation,
```suggestion
#' @param dry_run (logical) If `TRUE`, the code will do all checks before compilation,
```

2023-08-16 23:38 UTC, jgabry commented on R/model.R
> +    if(!is.null(cpp_options[["USER_HEADER"]]) || !is.null(cpp_options[["user_header"]])) {
```suggestion
    if (!is.null(cpp_options[["USER_HEADER"]]) || !is.null(cpp_options[["user_header"]])) {
```

2023-08-16 23:38 UTC, jgabry commented on R/model.R
> +      warning('User header specified both via cpp_options[["USER_HEADER"]] and cpp_options[["user_header"]]')
```suggestion
      warning('User header specified both via cpp_options[["USER_HEADER"]] and cpp_options[["user_header"]].', call. = FALSE)
```

2023-08-16 23:38 UTC, jgabry commented on R/model.R
> +      stop(paste0("User header file '", user_header, "' does not exist"))
```suggestion
      stop(paste0("User header file '", user_header, "' does not exist."), call. = FALSE)
```

2023-08-16 23:38 UTC, jgabry commented on R/model.R
> +            "currently available with WSLv1 CmdStan and will not be compiled",
```suggestion
            "currently available with WSLv1 CmdStan and will not be compiled.",
```

2023-08-23 10:52 UTC, rok-cesnovar approved these changes
Thanks!

2023-08-24 05:37 UTC, martinmodrak commented
Hi, just merged master back in. Could somebody merge this before it gets out of sync 🙏 ? Or is there something else to be done/approved?

2023-08-24 06:34 UTC, merged

2023-08-24 06:35 UTC, rok-cesnovar commented
I just assume the author can merge once its approved :) Thanks Martin!